ALTER TABLE "tables"
  ADD COLUMN IF NOT EXISTS "maxCapacity" INTEGER,
  ADD COLUMN IF NOT EXISTS "adjacentTableIds" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "reservations"
  ADD COLUMN IF NOT EXISTS "extraChair" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "combinedWithTableId" INTEGER,
  ADD COLUMN IF NOT EXISTS "combinedWithTableIds" JSONB NOT NULL DEFAULT '[]';
